### PR TITLE
move script scanner out of abstract servers.

### PR DESCRIPTION
**Pull request by jayich**
@aransfor , @gregllong 

fixes: https://github.com/CampbellGroup/common/issues/12

### CODE REVIEW

**Comment by gregllong** [comment]
Does the client file have to be modified accordingly?

**Comment by jayich** [comment]
@gregllong , I do not think so.  Can you check this branch real quick?  I think we should be in the clear.

**Comment by aransfor** [comment]
We should also clear this with @theoriginaljuice since he uses scriptscanner but I think the only change need to be made is in our master GUI's the import location has to change... should be straight forward but since this WILL technically break everyones code I want an all clear

**Comment by jayich** [comment]
It looks like in molecules we only import a script_scanner GUI into the command center (master GUI), nothing from the server.

**Comment by gregllong** [comment]
Seems like all clear for me. I think this works out because the GUI just look for the script_scanner server and not import it directly.

**Comment by gregllong** [comment]
I just searched for "abstractservers" in common. I don't think it's imported anywhere in clients, only in servers.

**Comment by gregllong** [comment]
LGTM

**Comment by aransfor** [comment]
LGTM once cleared by @theoriginaljuice

**Comment by jayich** [comment]
small update @gregllong , @aransfor

**Comment by gregllong** [comment]
LGTM

**Pull request merged**
