### PR TITLE
Amj/cut dv debug prints

### PR DESCRIPTION
**Pull request by jayich**
Review: @aransfor , @gregllong 

I set out to cut some print statements and ended up spending most of the time making style changes.

### CODE REVIEW

**Comment by gregllong** [comment]
LGTM

**Comment by aransfor** [comment]
I cant view the diff for some reason

**Comment by jayich** [comment]
The diff is too large for GitHub, it says to view the diff locally.

**Comment by aransfor** [comment]
LGTM

**Pull request merged**
