### PR TITLE
Amj/increase wm exposure limit

### PR DESCRIPTION
**Pull request by jayich**
Review: @aransfor , @theoriginaljuice , @gregllong 

Please take  look. @michaelip9228 wanted longer exposure times for the 369 channel.  Client appears to work.

### CODE REVIEW

**Comment by aransfor** [comment]
@jayich  what is the max setting for the wavemeter? I suppose it makes sense to set it to this. Also @theoriginaljuice have we decided if its possible to get control of the second interferometer exposure?

**Comment by jayich** [comment]
I do not know the max exposure time.

**Comment by gregllong** [comment]
LGTM

**Comment by aransfor** [comment]
I think we should look this up in the manual and adjust the max time to the wavemeter max

**Comment by theoriginaljuice** [comment]
The manual indicates up to 10s exposure. We might as well set it to the max. LGTM.

**Comment by theoriginaljuice** [comment]
@aransfor we can get the other interferometer amp. I can try and get that going. We'll need to add functionality to set its exposure as well.

**Comment by aransfor** [comment]
@theoriginaljuice awesome! you need a better icon for your avatar juice....

@jayich LGTM with the 5.0 s-> 10.0 s change

**Comment by jayich** [comment]
@theoriginaljuice , waiting for your okay.

**Comment by jayich** [comment]
bump @theoriginaljuice

**Comment by theoriginaljuice** [comment]
I refer to my original LGTM in my first comment.

**Comment by theoriginaljuice** [comment]
@jayich

**Pull request merged**
