### PR TITLE
Amr/wavemeterfixes3.0

### PR DESCRIPTION
**Pull request by aransfor**
This version is now running on the campbell wavemeter and works, essentially this just blocks individual channel locking on our wavemeter version

### CODE REVIEW

**Comment by jayich** [comment]
What is individual channel locking?

**Comment by aransfor** [comment]
The stupid wavemeter lock all channels or no channels, Justin found a hack to fix this but it appears not to work with our wavemeter

**Comment by jayich** [comment]
Ah, this is unfortunate.  So the wavemeters are slightly different and the wavemeter version number comes from the wavemeter device?

**Comment by aransfor** [comment]
Exactly

**Comment by jayich** [comment]
I imagine this is coming from the firmware?  We could possibly update the firmware?  It looks like you guys have devised another probably less painful/risky solution.

**Comment by aransfor** [comment]
For sure, this is on the back burner unless it becomes crucial

**Comment by jayich** [comment]
good deal.  I know you have better solutions in the laser stabilization pipeline.

**Comment by jayich** [comment]
LGTM.

**Comment by gregllong** [comment]
LGTM

**Comment by barium-project** [comment]
@aransfor tested this on our wavemeter and all is good to merge.

**Pull request merged**
