### PR TITLE
Change the server name to make it distinct from the original data_vault.

### PR DESCRIPTION
**Pull request by jayich**
Hard-coded the repository path from self.name to "Data Vault."

Review: @aransfor , @gregllong , @theoriginaljuice 

I expect this PR to take a while to implement.  I'm not sure about the hard-coded name change for the data vault path.

The intent here is not to have conflicts with the original Martinis group data vault.

I recommend branching your experiment repository, something like data_vault_cg, and try to get your code working with this PR.

### CODE REVIEW

**Comment by jayich** [comment]
https://github.comhttps://github.com/CampbellGroup/common/issues/93/CampbellGroup/common/issues/93

**Comment by gregllong** [comment]
LGTM

**Comment by gregllong** [comment]
# @aransfor @theoriginaljuice PLEASE NOTE: I learnt from Andrew just now that this piece of pull request is not likely to be compatible with your current experiment code if your code depends on the old datavault. You need to make sure you have changed the name of datavault you use in your code in order for this pull request to be compatible.

**Comment by aransfor** [comment]
Yes, I think this is a long term PR, I will start looking into it soon hopefully...

**Comment by theoriginaljuice** [comment]
LGTM. There are no issues for us since we have not implemented data vault yet.

**Comment by aransfor** [comment]
@jayich @gregllong 

So I have been thinking about this and after using scalabrad and the web interface it occurs to me a simple solution to this problem is to run multiple nodes on each machine. For example node_qsimexpcontrol.common, node_qsimexpcontrol.martinisservers, node_qsimexpcontrol.haeffnerservers. This resolves all node conflicts and allows us to switch between servers

**Comment by jayich** [comment]
@aransfor ,  this seems like a promising solution.  Let's discuss when I can make it back.

**Comment by jayich** [comment]
See https://github.com/labrad/pylabrad/issues/255#issuecomment-220701998

**Pull request closed without merging**
