### PR TITLE
Cutting sequences from common.

### PR DESCRIPTION
**Pull request by jayich**
Review: @aransfor , @gregllong

### CODE REVIEW

**Comment by aransfor** [comment]
LGTM

**Comment by gregllong** [comment]
LGTM

**Comment by michaelip9228** [comment]
LGTMT...

**Comment by aransfor** [comment]
@michaelip9228 @jayich @gregllong @theoriginaljuice  Michael has his game face on

**Comment by aransfor** [comment]
:+1:

**Pull request merged**
