### PR TITLE
mf/190 iXon remote client

### PR DESCRIPTION
**Pull request by fanmingyu212**
Added the functionality to support remote clients with AndorServer.py. Also added another client called iXonRemoteClient. This client can run on remote computers and use LabRAD connection to connect to the AndorServer.py. Though more improves are needed, these additions provide a possible way to control the camera and stream the live video on another computer without the needs for long video cables. The original functions of AndorServer.py are unmodified so the new code is fully compatible with the original features.

In order to use the remote client, set the self.camera_ip in AndorConfig.py in iXonRemoteClient folder to the ip address that the LabRAD server is on, and run AndorServer.py on the camera computer, and AndorClient.py on a remote computer.

Some issues with the server/client now:
1. The frames rate on remote client is about 1-2 frames/second, _and there could be lags in the video_ **(Lag problem should be solved with commit 6e4014e)**. https://github.com/CampbellGroup/common/blob/mf/190_iXon_remote_client/lib/servers/iXonServer/AndorServer.py#L485 _sets the loop time to 0.5 s, so maximum frame rate to 2 frames/second_ **(Setting it to 0.1 s in commit 6e4014e. Smaller value should work better)**. Some further work such as compressing the images may improve the performance.
2. If one changes the camera configurations (live video on/off, exposure time, em gain, etc.) via AndorServer.py, then AndorClient.py cannot update the UI with these changes until AndorClient.py is restarted.
3. It does not support live video on client and server at the same time. If the client is already running live video, clicking live video on server would not work. Same for trying to run client video when server live video is running.

### CODE REVIEW

**Comment by aransfor** [comment]
This looks like a good start to me!

**Comment by jayich** [comment]
https://github.com/CampbellGroup/common/issues/190

**Comment by aransfor** [comment]
@fanmingyu212 tried this out i get the following error:

  File "AndorClient.py", line 40, in connect
    yield self.server.signal__image_updated(IMAGE_UPDATED_SIGNAL)
exceptions.AttributeError: 'AsyncServerWrapper' object has no attribute 'signal__image_updated'
Unhandled error in Deferred:

**Comment by fanmingyu212** [comment]
@aransfor Could you check if self.camera_ip in iXonRemoteClient\AndorConfig.py has the IP of the LabRAD server which the camera server connects to? Also the camera server running needs to be the updated AndorServer.py in this branch instead of the AndorServer.py in the master branch. The updated server is fully compatible with the functionalities of the master branch server though.

It seems to be AndorClient.py is trying to connect to the master branch AndorServer.py, which does not have the signal__image_updated attribute. Stopping the AndorServer on LabRAD and running the AndorServer.py in this branch may help.

**Comment by aransfor** [comment]
I dont think its a good idea to emit video signal over the wire. @jayich @theoriginaljuice can chime in for other opinions

**Comment by fanmingyu212** [comment]
@aransfor I just want to clarify that the video signal is not emitted until the remote client asks for the signal. When the remote client stops live video, the video signal stops emitting too. Therefore if the remote client is not used, the server does not emit video signal, and it functions as same as the server before the change.

**Comment by jayich** [comment]
@aransfor the server will not emit any signal unless you use the remote client to tell the server to start emitting signal.

**Pull request merged**
