### PR TITLE
Labrad client now passes environment password to wavemeter computer

### PR DESCRIPTION
**Pull request by aransfor**
This should make us compatible with new and old labrad

### CODE REVIEW

**Comment by aransfor** [comment]
@ypark137 You should checkout this branch on you wavemeter client computer and see if it works and if the password issue is gone

**Comment by jayich** [comment]
Nice work, LGTM.  Dig the style upgrades.

**Comment by gregllong** [comment]
LGTM.

Faster than @michaelip9228  this time.

**Comment by aransfor** [comment]
@gregllong  you got :8ball: :8ball: ?

**Comment by gregllong** [comment]
Maybe we should merge this PR first, and branch the latest commits to another branch, something like "amr/new_node"?

**Comment by jayich** [comment]
Sounds good to me.  New content.

**Comment by jayich** [comment]
client looks fine.  LGTM.

**Comment by aransfor** [comment]
@gregllong its all related to the upgrade and the node is independant of everything... I can move it but I dont think its super necessary

**Comment by gregllong** [comment]
LGTM

**Comment by jayich** [comment]
@aransfor , please merge when you have a chance if you are happy with the changes.

**Pull request merged**
