### PR TITLE
Data vault saves values with arbitrary header (section name)

### PR DESCRIPTION
**Pull request by fanmingyu212**
Addresses #238.

Data vault can only save `Independent`, `Dependent`, `Parameter`, and `Comment` in the .ini file now. 

With this PR, data vault can save values with any header in the ,ini file (displayed as sections in the .ini).

An example .ini is shown below:

```ini
[General]
dtype = float
created = 2018-01-08, 17:59:21
accessed = 2018-06-16, 11:33:01
modified = 2018-01-08, 17:59:21
title = Photodiode
independent = 1
dependent = 1
parameters = 3
comments = 0
wavemeter_frequency = 2
temperature = 1

[Independent 1]
label = t
units = num

[Dependent 1]
label = Photodiode Voltage
units = V
category = 

[Parameter 1]
label = Window
data = ['photodiode']

[Parameter 2]
label = plotLive
data = True

[Parameter 3]
label = startTime
data = 1515463161.655

[wavemeter_frequency 1]
label = 422_nm
data = Value(711.0, 'THz')

[wavemeter_frequency 2]
label = 461_nm
data = Value(650.0, 'THz')

[temperature 1]
label = lab
data = Value(21.0, 'degC')

[Comments]

``` 

`wavemeter_frequency` and `temperature` are the new header names. Number of those sections are saved in `wavemeter_frequency` and `temperature` options in `General` section.

Also added data vault functions to add the headers and read the headers:
- `add_additional_header(self, c, header_name, name, data)` adds a new header.
e.g. `cxn.data_vault.add_additional_header("wavemeter_frequency", "422_nm", WithUnit(711, "THz"))`. Only lower case for the `header_name` is supported. It the `header_name` contains uppercase characters, it will be converted to lower case.
- `additional_headers(self, c)` returns all `header_name`, `label` pairs.
- `get_additional_header(self, c, header_name, name, case_sensitive)` reads a value in `header_name` sections with label `name`.
- `get_additional_headers(self, c)` returns all headers and values.

The headers are designed to work very similar to parameters, but with flexibility to rename the sections. It could provide new naming schemes for the values saved in .ini to allow better organization.

### CODE REVIEW

**Comment by aransfor** [comment]
I dont have time to look at this right now but it seems to me that you are just renaming the header meant to number parameters, e.g. 

[temperature 1]
label = lab
data = Value(21.0, 'degC')

could just be:

[parameter N]
label = lab temperature 1
data = Value(21.0, 'degC')

is this not equally as flexible with no code changes?

**Comment by jayich** [comment]
We would like control over the bracket ([]'s) namespace.  Right now you only have several fixed values.  This way we can define (in our lab) what is a "Parameter", and what would fall under other categories as the need arises.

This certainly can be done all through the "Parameter" value, but we want access to the bracket namespace for hierarchical organization.

@aransfor does this make sense?

**Comment by aransfor** [comment]
@jayich for sure I can see for organizational reasons. Give me a day or two to find time to go through the code but it should be straight forward

**Comment by jayich** [comment]
@theoriginaljuice @gregllong Can you guys please take a look at this code before Tony does to save him some time?  I feel like the majority of our PR's Tony is taking the time to look through.

**Pull request merged**
