### PR TITLE
Amj/andor config

### PR DESCRIPTION
**Pull request by jayich**
@aransfor , please check this branch when you have a chance.

@theoriginaljuice , review

### CODE REVIEW

**Comment by gregllong** [comment]
certainly looks good to me

**Comment by aransfor** [comment]
@jayich I think the PDF should be both here and on the server. Other than that the code seems to work

**Comment by aransfor** [comment]
LGTM besides the PDF

**Comment by theoriginaljuice** [comment]
LGTM

**Comment by jayich** [comment]
I don't think we should keep any pdfs in the repository.

**Pull request closed without merging**
