### PR TITLE
Tests that depend on hardware are being moved out of common/tests so …

### PR DESCRIPTION
**Pull request by jayich**
…that nosetests -w tests will be independent of hardware.

Review: @aransfor , @gregllong

### CODE REVIEW

**Comment by aransfor** [comment]
LGTM :8ball:

**Comment by gregllong** [comment]
LGTM.

@aransfor how did you get the billiard ball there?

**Comment by michaelip9228** [comment]
:8ball: :8ball: :8ball:

**Comment by aransfor** [comment]
@gregllong your getting trolled

**Pull request merged**
